### ISSUE TITLE
HTTP Error 404: Not Found during generating translated versions

### ISSUE THREAD

**Issue by Gracesta** [SamsungLabs/X-MRS#1]
When I tried `python translate_text.py <LANGUAGE>`  downloading from https://codeload.github.com/pytorch/fairseq/zip/master, I get this error:
`urllib.error.HTTPError: HTTP Error 404: Not Found`

It seems that the file doesn't exist?

**Comment by reg09** [comment]
Hi, I believe this error is due to fairseq changing their default branch name from master to main, pytroch.hub defaults to using master. This has been corrected in the latest pytorch / hub version. I have updated the requirements.txt to reflect the newest dependencies. Recreating the environment with these should solve the issue.
